version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - /
      - tools/go.mod
    schedule:
      interval: "monthly"
    groups:
      go-dependency:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"

