name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1" # Monday at 8am

jobs:
  go:
    uses: fredrikaverpil/github/.github/workflows/go.yml@main
    with:
      config-source: golden-latest
