name: go

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    uses: fredrikaverpil/github/.github/workflows/go.yml@main
    with:
      # comma-separated list of versions
      go-versions: 1.24.1 # rc versions are defined like 1.24.0-rc.3
      os-versions: ubuntu-latest
      golangci-config-source: golden-latest
